version: '3'

services:
  database:
    container_name: ${DATABASE_CONTAINER_NAME}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    image: mongo:7.0.4